baseURL = 'https://tilde.town/~kindrobot/'
languageCode = 'en-ca'
title = 'kindrobot'
relativeURLs = true

enableEmoji = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
