baseURL = 'https://tilde.town/~kindrobot/'
languageCode = 'en-ca'
title = 'kindrobot'
relativeURLs = true

enableEmoji = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes."text/ass"]
  suffixes = ["ass"]

[outputFormats]
  [outputFormats.ActuallySimpleSyndication]
    baseName = 'feed'
    isPlainText = true
    mediaType = 'text/ass'

[outputs]
  home = ['HTML', 'AMP', 'RSS', "ActuallySimpleSyndication"]
